### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by vizeke** [prodest/es-na-palma-da-mao-mobile#17]
__Objetivos__ - Aumente suas chances de chegar aonde você quer, definindo onde você quer estar.

Um bom Objetivo de Sprint deve ser _específico_ e _mensurável_, ajudando o time a ter um propósito comum.

* Melhorar o tempo de carregamento do aplicativo, as transições entre telas e animações dentro das telas. 
* Adicionar telas de consulta de multas e consulta de processos. 
* Refatoração do código para componentes, auxiliando na futura migração para typescript, angular 2 e ionic 2.

__Entregáveis__ - O que será entregue nessa Sprint. Usando o markup do GitHub nós conseguimos listar e acompanhar facilmente cada situação.

- [x] #9 - O desempenho do aplicativo pode ser melhorado 
- [x] #14 - Consulta de Processos (SEP)
- [x] #16  - Detran - Consulta de pontos CNH
- [x] #17 - Sprint Goal

__Métricas e Critérios__ - Quanto tempo a Sprint vai durar e quais são os critérios de aceitação? Incluindo essa informação fica fácil analisá-la futuramente.

A Sprint vai durar 2 semanas e será considerada um sucesso caso:

- [x] Tempo de carregamento inicial menor do que 5s
- [x] Acessar as 2 novas telas pelo dispositivo acessando dados de produção
- [x] Todo o código componentizado
